import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import MyCard from '@/components/MyCard'
import React from 'react'


function scrollToSection(e: React.MouseEvent, id: string) {
  e.preventDefault()
  const element = document.getElementById(id)
  element?.scrollIntoView({ behavior: 'smooth' })
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.sectionTitle}>
          <h1 className={styles.title}>Calendário Eleitoral 2024/25</h1>
          <div className={styles.subtitle}>
            <div>De acordo com a Resolução TSE nº 23.738/2024</div>
          </div>
        </section>
        <section className={styles.section}>
          <div className={styles.intro}>
            <div className={styles.texto}>
              Em 2024, o Brasil retorna às urnas para a renovação dos mandatos municipais. É um momento singular da nossa
              democracia, no qual todas as cidadãs e cidadãos são chamados a escolher seus representantes mais próximos – Prefeitas(os) e
              Vereadoras(es).
            </div>
            <div className={styles.texto}>
              No entanto, o processo eleitoral se inicia muito antes do dia 6 de outubro, data em que todos comparecem às urnas. Há
              regras e procedimentos exigidos de candidatos e eleitores muito antes dessa data, garantindo que as eleições ocorram dentro
              da legalidade, transparência e isonomia. As datas essenciais para esta eleição foram divulgadas pelo Tribunal Superior Eleitoral
              – TSE por meio da Resolução nº 23.738, de 2024 (Calendário Eleitoral das Eleições 2024).
            </div>
            <div className={styles.texto}>
              Este material apresenta – de forma interativa – a Resolução mencionada, com as datas e eventos importantes referentes
              ao pleito. Basta clicar na data de interesse no calendário para ser direcionado(a) ao conteúdo.
            </div>
            <div className={styles.texto}>
              Na expectativa de contribuir para o fortalecimento do exercício pleno da democracia, meus cordiais cumprimentos.
            </div>
          </div>
          <div className={styles.deputado}>
            <div className={styles.nome}>DEPUTADO SÓSTENES CAVALCANTE </div>
            <div>
              Segundo-Vice-Presidente da Câmara dos Deputados <br />
              Prolegis – Programa de Interação Legislativa
              </div>
          </div>

          <div className={styles.resolucao}>
            <a href="https://www.tse.jus.br/legislacao/compilada/res/2024/resolucao-no-23-738-de-27-de-fevereiro-de-2024">Resolução TSE nº 23.738/2024</a>
          </div>
        </section>

        <div className={styles.ano} id='calendario2024'>2024 </div >
        <div className={styles.container} >
          <section className={styles.cardsContainer}>
            <MyCard title='Janeiro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button className={styles.n}>05</button>
                  <button className={styles.n}>06</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>07</button>
                  <button className={styles.n}>08</button>
                  <button className={styles.n}>09</button>
                  <button className={styles.n}>10</button>
                  <button className={styles.n}>11</button>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button className={styles.n}>14</button>
                  <button className={styles.n}>15</button>
                  <button className={styles.n}>16</button>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button className={styles.n}>19</button>
                  <button className={styles.n}>20</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button className={styles.n}>21</button>
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button className={styles.n}>26</button>
                  <button className={styles.n}>27</button>
                </div>
                <div className={styles.fileira5}>
                  
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>
                  <button className={styles.n}>31</button>
                </div>
                
              </span>
            </MyCard>            
          </section>

          <section className={styles.cardsContainer}>
          <MyCard title='Fevereiro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

            <span>
              <div className={styles.fileira1}>
                <button className={styles.n}>01</button>
                <button className={styles.n}>02</button>
                <button className={styles.n}>03</button>
                           
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>04</button>
                <button className={styles.n}>05</button>
                <button className={styles.n}>06</button> 
                <button className={styles.n}>07</button>
                <button className={styles.n}>08</button>
                <button className={styles.n}>09</button>
                <button className={styles.n}>10</button>
                
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>11</button>
                <button className={styles.n}>12</button>
                <button className={styles.n}>13</button>
                <button className={styles.n}>14</button>
                <button className={styles.n}>15</button>
                <button className={styles.n}>16</button>
                <button className={styles.n}>17</button>
                
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>18</button>
                <button className={styles.n}>19</button>
                <button className={styles.n}>20</button>
                <button className={styles.n}>21</button>
                <button className={styles.n}>22</button>
                <button className={styles.n}>23</button>
                <button className={styles.n}>24</button>
                
              </div>
              <div className={styles.fileira5}>
                <button className={styles.n}>25</button>
                <button className={styles.n}>26</button>
                <button className={styles.n}>27</button>
                <button className={styles.n}>28</button>
                <button className={styles.n}>29</button>
              </div>
              
            </span>
          </MyCard>
          
          
        </section>
          <section className={styles.cardsContainer}>
            <MyCard title='Março' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5marco')} className={styles.data}>05</button>
                  <button className={styles.n}>06</button>
                  
                  <button onClick={(e) => scrollToSection(e, '7marco')} className={styles.data}>07</button>
                  <button className={styles.n}>08</button>
                  <button className={styles.n}>09</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>10</button>
                  <button className={styles.n}>11</button>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                  <button className={styles.n}>14</button>
                  <button className={styles.n}>15</button>
                  <button className={styles.n}>16</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button className={styles.n}>19</button>
                  <button className={styles.n}>20</button>
                  <button className={styles.n}>21</button>
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  
                </div>
                <div className={styles.fileira5}>
                  <button className={styles.especial}>24/31</button>
                  <button className={styles.n}>25</button>
                  <button className={styles.n}>26</button>
                  <button className={styles.n}>27</button>
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>                  
                </div>
              
              </span>
            </MyCard>           
          </section> 

          <section className={styles.cardsContainer}>
            <MyCard title='Abril' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button onClick={(e) => scrollToSection(e, '1abril')} className={styles.data}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5abril')} className={styles.data}>05</button>
                  <button onClick={(e) => scrollToSection(e, '6abril')} className={styles.data}>06</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>07</button>
                  <button onClick={(e) => scrollToSection(e, '8abril')} className={styles.data}>08</button>
                  <button onClick={(e) => scrollToSection(e, '9abril')} className={styles.data}>09</button>
                  <button className={styles.n}>10</button>
                  <button className={styles.n}>11</button>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button className={styles.n}>14</button>
                  <button className={styles.n}>15</button>
                  <button className={styles.n}>16</button>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button className={styles.n}>19</button>
                  <button className={styles.n}>20</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button className={styles.n}>21</button>
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button className={styles.n}>26</button>
                  <button className={styles.n}>27</button>
                </div>
                <div className={styles.fileira5}>
                  
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>                  
                </div>
                
              </span>
            </MyCard>
          </section>     
        </div>
        <div className={styles.container}>
          <section className={styles.cardsContainer}>
            <MyCard title='Maio' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>05</button>
                  <button className={styles.n}>06</button>
                  <button className={styles.n}>07</button>
                  <button onClick={(e) => scrollToSection(e, '8maio')} className={styles.data}>08</button>
                  <button onClick={(e) => scrollToSection(e, '9maio')} className={styles.data}>09</button>
                  <button className={styles.n}>10</button>
                  <button className={styles.n}>11</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                  <button className={styles.n}>14</button>
                  <button onClick={(e) => scrollToSection(e, '15maio')} className={styles.data}>15</button>
                  <button className={styles.n}>16</button>
                  <button onClick={(e) => scrollToSection(e, '17maio')} className={styles.data}>17</button>
                  <button className={styles.n}>18</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>19</button>
                  <button className={styles.n}>20</button>
                  <button className={styles.n}>21</button>
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  
                </div>
                <div className={styles.fileira5}>
                  <button className={styles.n}>26</button>
                  <button className={styles.n}>27</button>
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>
                  <button className={styles.n}>31</button>
                </div>
                
              </span>
            </MyCard>
          </section>

          <section className={styles.cardsContainer}>
            <MyCard title='Junho' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

            <span>
              <div className={styles.fileira1}>
                <button className={styles.n}>01</button>
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>02</button>
                <button onClick={(e) => scrollToSection(e, '3junho')} className={styles.data}>03</button>
                <button className={styles.n}>04</button>
                <button onClick={(e) => scrollToSection(e, '5junho')} className={styles.data}>05</button>
                <button className={styles.n}>06</button>
                <button className={styles.n}>07</button>
                <button className={styles.n}>08</button>
                
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>09</button>
                <button className={styles.n}>10</button>
                <button className={styles.n}>11</button>
                <button className={styles.n}>12</button>
                <button className={styles.n}>13</button>
                <button className={styles.n}>14</button>
                <button className={styles.n}>15</button>
                
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>16</button>
                <button onClick={(e) => scrollToSection(e, '17junho')} className={styles.data}>17</button>
                <button className={styles.n}>18</button>
                <button className={styles.n}>19</button>
                <button onClick={(e) => scrollToSection(e, '20junho')} className={styles.data}>20</button>
                <button className={styles.n}>21</button>
                <button className={styles.n}>22</button>
                
                
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>23</button>
                <button className={styles.n}>24</button>
                <button className={styles.n}>25</button>
                <button className={styles.n}>26</button>
                <button className={styles.n}>27</button>
                <button className={styles.n}>28</button>
                <button className={styles.n}>29</button>
              </div>
              <div className={styles.fileira5}>
                <button onClick={(e) => scrollToSection(e, '30junho')} className={styles.data}>30</button>                
              </div>
              
            </span>
            </MyCard>
          </section>

          <section className={styles.cardsContainer}>
            <MyCard title='Julho' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>
              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5julho')} className={styles.data}>05</button>
                  <button onClick={(e) => scrollToSection(e, '6julho')} className={styles.data}>06</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>07</button>
                  <button onClick={(e) => scrollToSection(e, '8julho')} className={styles.data}>08</button>
                  <button onClick={(e) => scrollToSection(e, '9julho')} className={styles.data}>09</button>
                  <button className={styles.n}>10</button>
                  <button className={styles.n}>11</button>
                  <button onClick={(e) => scrollToSection(e, '12julho')} className={styles.data}>12</button>
                  <button className={styles.n}>13</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button className={styles.n}>14</button>
                  <button className={styles.n}>15</button>
                  <button onClick={(e) => scrollToSection(e, '16julho')} className={styles.data}>16</button>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button onClick={(e) => scrollToSection(e, '19julho')} className={styles.data}>19</button>
                  <button onClick={(e) => scrollToSection(e, '20julho')} className={styles.data}>20</button>
                </div>
                <div className={styles.fileira}>
                  
                  <button onClick={(e) => scrollToSection(e, '21julho')} className={styles.data}>21</button>
                  <button onClick={(e) => scrollToSection(e, '22julho')} className={styles.data}>22</button>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button onClick={(e) => scrollToSection(e, '26julho')} className={styles.data}>26</button>
                  <button className={styles.n}>27</button>
                </div>
                <div className={styles.fileira5}>
                  
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button onClick={(e) => scrollToSection(e, '30julho')} className={styles.data}>30</button>
                  <button className={styles.n}>31</button>
                </div>
                
              </span>
            </MyCard>
          </section>

          <section className={styles.cardsContainer}>
            <MyCard title='Agosto' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>                                  
                </div>
                <div className={styles.fileira}>
                  <button onClick={(e) => scrollToSection(e, '4agosto')} className={styles.data}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5agosto')} className={styles.data}>05</button>
                  <button onClick={(e) => scrollToSection(e, '6agosto')} className={styles.data}>06</button>
                  <button onClick={(e) => scrollToSection(e, '7agosto')} className={styles.data}>07</button>
                  <button className={styles.n}>08</button>
                  <button className={styles.n}>09</button>
                  <button className={styles.n}>10</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>11</button>
                  <button className={styles.n}>12</button>
                  <button onClick={(e) => scrollToSection(e, '13agosto')} className={styles.data}>13</button>
                  <button className={styles.n}>14</button>
                  <button onClick={(e) => scrollToSection(e, '15agosto')} className={styles.data}>15</button>
                  <button onClick={(e) => scrollToSection(e, '16agosto')} className={styles.data}>16</button>
                  <button onClick={(e) => scrollToSection(e, '17agosto')} className={styles.data}>17</button>
                 
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>18</button>
                  <button className={styles.n}>19</button>
                  <button onClick={(e) => scrollToSection(e, '20agosto')} className={styles.data}>20</button>
                  <button className={styles.n}>21</button>
                  <button onClick={(e) => scrollToSection(e, '22agosto')} className={styles.data}>22</button>
                  <button onClick={(e) => scrollToSection(e, '23agosto')} className={styles.data}>23</button>
                  <button className={styles.n}>24</button>
                  
                </div>
                <div className={styles.fileira5}>
                  <button onClick={(e) => scrollToSection(e, '25agosto')} className={styles.data}>25</button>
                  <button className={styles.n}>26</button>
                  <button onClick={(e) => scrollToSection(e, '27agosto')} className={styles.data}>27</button>
                  <button onClick={(e) => scrollToSection(e, '28agosto')} className={styles.data}>28</button>
                  <button onClick={(e) => scrollToSection(e, '29agosto')} className={styles.data}>29</button>
                  <button onClick={(e) => scrollToSection(e, '30agosto')} className={styles.data}>30</button>
                  <button className={styles.n}>31</button>
                </div>
                
              </span>
            </MyCard>
          </section>     
        </div>

        <div className={styles.container}>
          <section className={styles.cardsContainer}>
            <MyCard title='Setembro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>
              <span>
                <div className={styles.fileira1}>
                  <button onClick={(e) => scrollToSection(e, '1setembro')} className={styles.data}>01</button>
                </div>
                <div className={styles.fileira}>
                  <button onClick={(e) => scrollToSection(e, '2setembro')} className={styles.data}>02</button>
                  <button onClick={(e) => scrollToSection(e, '3setembro')} className={styles.data}>03</button>
                  <button className={styles.n}>04</button>
                  <button className={styles.n}>05</button>
                  <button onClick={(e) => scrollToSection(e, '6setembro')} className={styles.data}>06</button>
                  <button className={styles.n}>07</button>
                  <button className={styles.n}>08</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button onClick={(e) => scrollToSection(e, '9setembro')} className={styles.data}>09</button>
                  <button className={styles.n}>10</button>
                  <button onClick={(e) => scrollToSection(e, '11setembro')} className={styles.data}>11</button>
                  <button className={styles.n}>12</button>
                  <button onClick={(e) => scrollToSection(e, '13setembro')} className={styles.data}>13</button>
                  <button onClick={(e) => scrollToSection(e, '14setembro')} className={styles.data}>14</button>
                  <button onClick={(e) => scrollToSection(e, '15setembro')} className={styles.data}>15</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button onClick={(e) => scrollToSection(e, '16setembro')} className={styles.data}>16</button>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button className={styles.n}>19</button>
                  <button className={styles.n}>20</button>
                  <button onClick={(e) => scrollToSection(e, '21setembro')} className={styles.data}>21</button>
                  <button className={styles.n}>22</button>
                  
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button onClick={(e) => scrollToSection(e, '26setembro')} className={styles.data}>26</button>
                  <button className={styles.n}>27</button>
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                </div>
                <div className={styles.fileira5}>
                  <button onClick={(e) => scrollToSection(e, '30setembro')} className={styles.data}>30</button>                
                </div>
                
              </span>
            </MyCard>
          </section>

          <section className={styles.cardsContainer}>
          <MyCard title='Outubro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

            <span>
              <div className={styles.fileira1}>
                <button onClick={(e) => scrollToSection(e, '1outubro')} className={styles.data}>01</button>
                <button className={styles.n}>02</button>
                <button onClick={(e) => scrollToSection(e, '3outubro')} className={styles.data}>03</button>
                <button onClick={(e) => scrollToSection(e, '4outubro')} className={styles.data}>04</button>
                <button onClick={(e) => scrollToSection(e, '5outubro')} className={styles.data}>05</button>
                
                
              </div>
              <div className={styles.fileira}>
                <button onClick={(e) => scrollToSection(e, '6outubro')} className={styles.data}>06</button>
                <button onClick={(e) => scrollToSection(e, '7outubro')} className={styles.data}>07</button>
                <button onClick={(e) => scrollToSection(e, '8outubro')} className={styles.data}>08</button>
                <button onClick={(e) => scrollToSection(e, '9outubro')} className={styles.data}>09</button>
                <button className={styles.n}>10</button>
                <button onClick={(e) => scrollToSection(e, '11outubro')} className={styles.data}>11</button>
                <button onClick={(e) => scrollToSection(e, '12outubro')} className={styles.data}>12</button>
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>13</button>
                <button onClick={(e) => scrollToSection(e, '14outubro')} className={styles.data}>14</button>
                <button onClick={(e) => scrollToSection(e, '15outubro')} className={styles.data}>15</button>
                <button className={styles.n}>16</button>
                <button onClick={(e) => scrollToSection(e, '17outubro')} className={styles.data}>17</button>
                <button className={styles.n}>18</button>
                <button onClick={(e) => scrollToSection(e, '19outubro')} className={styles.data}>19</button>
              </div>
              <div className={styles.fileira}>
                <button className={styles.n}>20</button>
                <button onClick={(e) => scrollToSection(e, '21outubro')} className={styles.data}>21</button>
                <button onClick={(e) => scrollToSection(e, '22outubro')} className={styles.data}>22</button>
                <button className={styles.n}>23</button>
                <button onClick={(e) => scrollToSection(e, '24outubro')} className={styles.data}>24</button>
                <button onClick={(e) => scrollToSection(e, '25outubro')} className={styles.data}>25</button>
                <button onClick={(e) => scrollToSection(e, '26outubro')} className={styles.data}>26</button>
              </div>
              <div className={styles.fileira5}>
                <button onClick={(e) => scrollToSection(e, '27outubro')} className={styles.data}>27</button>                
                <button onClick={(e) => scrollToSection(e, '28outubro')} className={styles.data}>28</button>
                <button onClick={(e) => scrollToSection(e, '29outubro')} className={styles.data}>29</button>
                <button onClick={(e) => scrollToSection(e, '30outubro')} className={styles.data}>30</button>
                <button className={styles.n}>31</button>
              </div>              
            </span>
          </MyCard> 
        </section>

        <section className={styles.cardsContainer}>
            <MyCard title='Novembro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button onClick={(e) => scrollToSection(e, '1novembro')} className={styles.data}>01</button>
                  <button className={styles.n}>02</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5novembro')} className={styles.data}>05</button>
                  <button className={styles.n}>06</button>
                  
                  <button className={styles.n}>07</button>
                  <button onClick={(e) => scrollToSection(e, '8novembro')} className={styles.data}>08</button>
                  <button className={styles.n}>09</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button onClick={(e) => scrollToSection(e, '10novembro')} className={styles.data}>10</button>
                  <button onClick={(e) => scrollToSection(e, '11novembro')} className={styles.data}>11</button>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                  <button className={styles.n}>14</button>
                  <button className={styles.n}>15</button>
                  <button onClick={(e) => scrollToSection(e, '16novembro')} className={styles.data}>16</button>
                  
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button onClick={(e) => scrollToSection(e, '19novembro')} className={styles.data}>19</button>
                  <button className={styles.n}>20</button>
                  <button className={styles.n}>21</button>
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  
                </div>
                <div className={styles.fileira5}>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button onClick={(e) => scrollToSection(e, '26novembro')} className={styles.data}>26</button>
                  <button className={styles.n}>27</button>
                  <button className={styles.n}>28</button>
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>                  
                </div>
              
              </span>
            </MyCard>
            
            
          </section> 
          <section className={styles.cardsContainer}>
            <MyCard title='Dezembro' subtitle='Dom | Seg | Ter | Qua | Qui | Sex | Sab'>

              <span>
                <div className={styles.fileira1}>
                  <button className={styles.n}>01</button>
                  <button className={styles.n}>02</button>
                  <button className={styles.n}>03</button>
                  <button className={styles.n}>04</button>
                  <button onClick={(e) => scrollToSection(e, '5dezembro')} className={styles.data}>05</button>
                  <button className={styles.n}>06</button>
                  <button className={styles.n}>07</button>
                </div>
                <div className={styles.fileira}>
                  <button className={styles.n}>08</button>
                  <button className={styles.n}>09</button>
                  <button className={styles.n}>10</button>
                  <button onClick={(e) => scrollToSection(e, '11dezembro')} className={styles.data}>11</button>
                  <button className={styles.n}>12</button>
                  <button className={styles.n}>13</button>
                  <button className={styles.n}>14</button>
                </div>
                <div className={styles.fileira}>                  
                  <button className={styles.n}>15</button>
                  <button onClick={(e) => scrollToSection(e, '16dezembro')} className={styles.data}>16</button>
                  <button className={styles.n}>17</button>
                  <button className={styles.n}>18</button>
                  <button onClick={(e) => scrollToSection(e, '19dezembro')} className={styles.data}>19</button>
                  <button className={styles.n}>20</button>
                  <button className={styles.n}>21</button>
                </div>
                <div className={styles.fileira}>                  
                  <button className={styles.n}>22</button>
                  <button className={styles.n}>23</button>
                  <button className={styles.n}>24</button>
                  <button className={styles.n}>25</button>
                  <button className={styles.n}>26</button>
                  <button className={styles.n}>27</button>
                  <button className={styles.n}>28</button>
                </div>
                <div className={styles.fileira5}>                  
                  <button className={styles.n}>29</button>
                  <button className={styles.n}>30</button>
                  <button onClick={(e) => scrollToSection(e, '31dezembro')} className={styles.data}>31</button>
                </div>
                
              </span>
            </MyCard>
            
            
          </section>     
        </div>
        
        <div className={styles.meses}>
          <div className={styles.mes}>
            <h1>Março</h1>
            <ul>
              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>5 de Março - Terça-Feira</div>
                </li>
                <div>
                  Data-limite para o Tribunal Superior Eleitoral expedir as instruções relativas às eleições municipais de 2024 (Lei nº 9.504/1997, art. 105, caput e § 3º).
                </div>
              </section>

            <section className={styles.sec} id='7marco'>
              <li>
                <div className={styles.dia}>7 de Março - Quinta-Feira</div>
              </li>
              <div>
                Data a partir da qual e até 5 de abril de 2024, considera-se justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
              </div>
            </section>
            </ul>
          </div>
          <div className={styles.mes}>
            <h1>Abril</h1>
            <ul>
              <section className={styles.sec} id='1abril'>
                <li>
                  <div className={styles.dia}>1 de Abril - Segunda-Feira</div>
                </li>
                <div>
                  Data a partir da qual e até 30 de julho de 2024, o Tribunal Superior Eleitoral promoverá, em até 5 (cinco) minutos diários, contínuos ou não, requisitados às emissoras de rádio e de televisão, propaganda institucional destinada a incentivar a participação feminina, das(dos) jovens e da comunidade negra na política e a esclarecer cidadãs e cidadãos sobre as regras e o funcionamento do sistema eleitoral brasileiro (Lei nº 9.504/1997, art. 93-A; Res-TSE nº 23.610, art. 116). 
                </div>
              </section>
              
              <section className={styles.sec} id='5abril'>
                <li>
                  <div className={styles.dia}>5 de Abril - Sexta-Feira</div>
                </li>
                <div>
                  Último dia do período em que se considera justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
                </div>
              </section>
              
              <section className={styles.sec} id='6abril'>
                <li>
                  <div className={styles.dia}>6 de Abril - Sábado (6 meses antes do 1º turno)</div>
                </li>
                <div>
                    <ol>
                      <li>Data-limite para registro, no Tribunal Superior Eleitoral, dos estatutos de partidos políticos e federações que poderão participar das eleições de 2024 (Lei nº 9.504/1997, arts. 4º e 6º-A, parágrafo único; Lei nº 9.096/1995, art. 11-A; Res.-TSE nº 23.609, art. 2º, I e II, primeira parte).</li>
                      <li>Data-limite para que a pessoa que pretenda se candidatar nas eleições de 2024 esteja com domicílio eleitoral no Município em que deseja concorrer e, desde que o estatuto partidário não estabeleça prazo superior, esteja filiada ao partido político pelo qual deseja ser inscrita (Lei nº 9.504/1997, art. 9º, caput; Lei nº 9.096/1995, art. 20, caput; e Res.-TSE nº 23.609, art. 10).</li>
                      <li>Data até a qual a(o) Presidente da República, as Governadoras, os Governadores, as Prefeitas e os Prefeitos que pretendam concorrer a outros cargos renunciem aos mandatos em exercício. (Constituição Federal, art. 14, § 6º; e Res.-TSE nº 23.609, art. 13).</li>
                    </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='8abril'>
                <li>
                  <div className={styles.dia}>8 de Abril - Segunda-Feira</div>
                </li>
                <div>
                  Último dia para que eleitoras e eleitores domiciliados(as) no Brasil que não possuem cadastro biométrico na Justiça Eleitoral solicitem operações de alistamento, transferência e revisão pelo serviço de autoatendimento eleitoral na internet.
                </div>
              </section>
              
              <section className={styles.sec} id='9abril'>
                <li>
                  <div className={styles.dia}>9 de Abril - Terça-Feira (180 dias antes do 1º turno)</div>
                </li>
                <div>
                    <ol>
                      <li>Último dia para o órgão de direção nacional do partido político ou da federação, que pretenda participar das eleições de 2024, fazer publicar, no Diário Oficial da União, na hipótese de omissão do estatuto, as normas para escolha e substituição de candidatas e candidatos e para a formação de coligações (Lei nº 9.504/1997, art. 7º, § 1º e Res.-TSE nº 23.609 art. 3º, § 3º).</li>
                      <li>Data a partir da qual, até a posse das pessoas eleitas, é vedado às(aos) agentes públicos fazer, na circunscrição do pleito, revisão geral da remuneração das servidoras públicas e dos servidores públicos que exceda a recomposição da perda de seu poder aquisitivo ao longo do ano da eleição (Lei nº 9.504/1997, art. 73, VIII).</li>
                    </ol>
                </div>
              </section>
              
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Maio</h1>
            <ul>
              <section className={styles.sec} id='8maio'>
                <li>
                  <div className={styles.dia}>8 de Maio - Quarta-Feira</div>
                </li>
                <div>
                  <ol>
                    
                    <li>Último dia para o recebimento de solicitações de operações de alistamento, transferência e revisão eleitoral em todas as unidades da Justiça Eleitoral e no serviço de autoatendimento na internet.</li>
                    
                    <li>Último dia para que as presas e os presos provisórios e as(os) adolescentes internadas(os), sem inscrição eleitoral regular no Município onde estejam, sejam alistadas(os) ou requeiram a regularização de sua situação para votarem nas eleições de 2024, mediante revisão ou transferência do título eleitoral (Lei nº 9.504/1997, art. 91, caput; e Res.-TSE nº 23.659/2021, art. 12, parágrafo único).</li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='9maio'>
                <li>
                  <div className={styles.dia}>9 de Maio - Quinta-Feira</div>
                </li>
                <div>
                  Data a partir da qual, até 5 de novembro de 2024, fica suspenso o recebimento de solicitações de operações de alistamento, transferência e revisão eleitoral em todas as unidades da Justiça Eleitoral e no serviço de autoatendimento na internet (Lei nº 9.504/1997, art. 91).
                </div>
              </section>
              
              <section className={styles.sec} id='15maio'>
                <li>
                  <div className={styles.dia}>15 de Maio - Quarta-Feira</div>
                </li>
                <div>
                  <ol>
                    
                    <li>Data a partir da qual, até 17 de maio de 2024, será realizado o Teste de Confirmação das correções aplicadas decorrentes dos resultados obtidos no Teste Público de Segurança da Urna 2023 (TPS), ocorrido no período de 27 de novembro a 1º de dezembro de 2023 no Tribunal Superior Eleitoral.</li>
                    
                    <li>Data a partir da qual é facultada a pré-candidatas e pré-candidatos a arrecadação prévia de recursos na modalidade de financiamento coletivo, ficando a liberação de recursos por entidades arrecadadoras condicionada ao cumprimento, pela candidata ou pelo candidato, do registro de sua candidatura, da obtenção do CNPJ e da abertura de conta bancária (Lei nº 9.504 /1997, art. 22-A, § 3º; e Res.-TSE nº 23.607/2019, art. 22, § 4º).</li>
                    
                    <li>Data a partir da qual é permitida a campanha de arrecadação prévia de recursos na modalidade de financiamento coletivo, observadas a vedação a pedido de voto e as regras relativas à propaganda eleitoral na internet (Lei nº 9.504/1997, art. 22-A, § 3º; e Res.-TSE nº 23.610/2019, art. 3º, § 4º).</li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='17maio'>
                <li>
                  <div className={styles.dia}>17 de Maio - Sexta-Feira</div>
                </li>
                <div>
                Último dia do Teste de Confirmação das correções aplicadas decorrentes dos resultados obtidos no Teste Público de Segurança da Urna 2023 (TPS) ocorrido no período de 27 de novembro a 1º de dezembro de 2023 no Tribunal Superior Eleitoral.
                </div> 
              </section>
               
            </ul>          
          </div>
          <div className={styles.mes}>
            <h1>Junho</h1>
            <ul>
              <section className={styles.sec} id='3junho'>
                <li>
                  <div className={styles.dia}>3 de Junho - Segunda-Feira</div>
                </li>
                <div>
                  Data-limite para que os partidos políticos comuniquem ao Tribunal Superior Eleitoral a renúncia ao Fundo Especial de Financiamento de Campanha (FEFC) (Lei nº 9.504/1997, art. 16-C, § 16; e Res.- TSE nº 23.605/2019 art. 2º, § 2º).
                </div>
              </section>
              
              <section className={styles.sec} id='5junho'>
                <li>
                  <div className={styles.dia}>5 de Junho - Quarta-Feira</div>
                </li>
                <div>
                  Data-limite para a Justiça Eleitoral disponibilizar aos partidos políticos a relação de todas(os) as(os) devedores de multa eleitoral, a qual embasará a expedição das certidões de quitação (Lei nº 9.504/1997, art. 11, § 9º).
                </div>
              </section>
              
              <section className={styles.sec} id='17junho'>
                <li>
                  <div className={styles.dia}>17 de Junho - Segunda-Feira</div>
                </li>
                <div>
                  Data limite para o Tribunal Superior Eleitoral divulgar o montante de recursos disponíveis no Fundo Especial de Financiamento de Campanha (FEFC), observados 15 (quinze) dias a partir do recebimento da dotação orçamentária pelo Tribunal (Lei nº 9.504/1997, art. 16-C, § 2º; e Res.-TSE nº 23.605/2019, art. 3º).
                </div>
              </section>
              
              <section className={styles.sec} id='20junho'>
                <li>
                  <div className={styles.dia}>20 de Junho - Quinta-Feira</div>
                </li>
                <div>
                  Último dia para o diretório nacional da federação, após definir o(s) partido(s) político(s) federado(s) que poderá(ão) obter a chave de acesso ao Sistema de Candidaturas – Módulo Externo (CANDex), informar ao Tribunal Superior Eleitoral, por formulário próprio, as unidades da federação em que, se for o caso, deverá ser inibida a concessão da chave a outro(s) partido(s) político(s) federados (Res.-TSE nº 23.609/2019, art. 6º, §6º-A, I).
                </div>
              </section>
              
              <section className={styles.sec} id='30junho'>
                <li>
                  <div className={styles.dia}>30 de Junho - Domingo</div>
                </li>
                <div>
                  Data a partir da qual é vedado às emissoras de rádio e de televisão transmitir programa apresentado ou comentado por pré-candidata ou pré-candidato (Lei nº 9.504/1997, art. 45, § 1º e Res.-TSE nº 23.610/2019, art. 43, § 2º).
                </div>
              </section>
              
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Julho</h1>
            <ul>
              <section className={styles.sec} id='5julho'>
                <li>
                  <div className={styles.dia}>5 de Julho - Sexta-Feira</div>
                </li>
                <div>
                  Data a partir da qual, se estiver em curso o período de 15 (quinze) dias que antecede à convenção do partido político ou da federação para escolha de candidatas e candidatos, é permitida a realização de propaganda intrapartidária, para indicação de nomes para concorrer aos cargos de prefeito, vice-prefeito e vereador, vedado o uso de rádio, televisão e outdoor e devendo a propaganda ser removida imediatamente após a convenção (Lei nº 9.504/1997, art. 36, § 1º e Res.-TSE nº 23.610/2019, art. 2º, § 1º).
                </div>
              </section>
              

              <section className={styles.sec} id='6julho'>
                <li>
                  <div className={styles.dia}>6 de Julho - Sábado (3 meses antes do 1° turno)</div>
                </li>
                <div>
                  <ol>
                    
                    <li>Data a partir da qual, até 6 de janeiro de 2025, órgãos e entidades da Administração Pública direta e indireta poderão ceder funcionárias e funcionários à Justiça Eleitoral, em casos específicos e de forma motivada, quando solicitadas(os) pelos tribunais eleitorais (Lei nº 9.504/1997, art. 94-A, II), aplicando-se esse calendário para as unidades da Federação que realizarem apenas o 1º turno. Esse prazo estende-se até 27 de janeiro de 2025, para as entidades estatais que realizarem 2º turno de eleições,</li>
                    
                    <li>Data a partir da qual e até a posse das(dos) eleitas(os), é proibido às agentes e aos agentes públicas(os), servidoras e servidores ou não, na circunscrição do pleito, sob pena de nulidade de pleno direito, nomear, contratar ou por qualquer forma admitir, dispensar sem justa causa, suprimir ou readaptar vantagens ou por outros meios dificultar ou impedir o exercício funcional e, ainda, de ofício, remover, transferir ou exonerar pessoa servidora pública, ressalvadas (Lei nº 9.504/1997, art. 73, V):
                      <ul>
                        
                        <li>a nomeação ou exoneração de cargos em comissão e designação ou dispensa de funções de confiança;</li>
                        
                        <li>a nomeação para cargos do Poder Judiciário, do Ministério Público, dos tribunais ou conselhos de contas e dos órgãos da Presidência da República;</li>
                        
                        <li>a nomeação das aprovadas e dos aprovados em concursos públicos homologados até 6 de julho de 2024;</li>
                        
                        <li>a nomeação ou contratação necessária à instalação ou ao funcionamento inadiável de serviços públicos essenciais, com prévia e expressa autorização da(o) Chefe do Poder Executivo; e</li>
                        
                        <li>a transferência ou remoção de ofício de militares, de policiais civis e de agentes penitenciárias(os).</li>
                      </ul>
                    </li>
                    
                    <li>Data a partir da qual, até a realização das eleições, são proibidas às agentes e aos agentes públicas(os), servidoras e servidores ou não (Lei nº 9.504/1997, art. 73, VI):
                      <ul>
                        
                        <li>realizar transferência voluntária de recursos da União aos Estados e Municípios e dos Estados aos Municípios, sob pena de nulidade absoluta, ressalvados os recursos destinados a cumprir obrigação formal preexistente para a execução de obra ou serviço em andamento e com cronograma prefixado, e os destinados a atender situações de emergência e de calamidade pública, objetiva e formalmente justificadas;</li>
                        
                        <li>com exceção da propaganda de produtos e serviços com concorrência no mercado, autorizar publicidade institucional de atos, programas, obras, serviços e campanhas dos órgãos públicos ou das respectivas entidades da Administração indireta, salvo em caso de grave e urgente necessidade pública, assim reconhecida pela Justiça Eleitoral;</li>
                        
                        <li>fazer pronunciamento em cadeia de rádio e de televisão fora do horário eleitoral gratuito, salvo quando, a critério da Justiça Eleitoral, tratar-se de matéria urgente, relevante e de funções de governo.</li>
                      </ul>
                    </li>
                    
                    <li>
                      Data a partir da qual as(os) agentes públicas(os) devem adotar as providências necessárias para que o conteúdo dos sítios, canais e outros meios de informação oficial exclua nomes, slogans, símbolos, expressões, imagens ou outros elementos que permitam identificar autoridades, governos ou administrações, cujos cargos estejam em disputa na campanha eleitoral, ainda que a divulgação tenha sido autorizada em momento anterior, assegurada a manutenção das informações necessárias para estrito cumprimento, pelos responsáveis, do previsto no art. 48-A da Lei Complementar nº 101/2000, nos arts. 8º e 10 da Lei nº 12.527/2011 e no §2º do art. 29 da Lei nº 14.129/2021.
                    </li>
                    
                    <li>
                      Data a partir da qual é vedada, na realização de inaugurações de obras públicas ou divulgação de prestação de serviços públicos, a contratação de shows artísticos pagos com recursos públicos (Lei nº 9.504/1997, art. 75).
                    </li>
                    
                    <li>
                    Data a partir da qual é proibido a candidata ou candidato comparecer a inaugurações de obras públicas (Lei nº 9.504/1997, art. 77).
                    </li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='8julho'>
                <li>
                  <div className={styles.dia}>8 de Julho - Segunda-Feira (90 dias antes do 1° turno)</div>
                </li>
                <div>
                  <ol>
                    
                    <li>Último dia para entidades fiscalizadoras, que desenvolveram programa próprio de verificação, entregarem à Secretaria de Tecnologia da Informação do Tribunal Superior Eleitoral, para homologação, os códigos-fonte dos programas de verificação e a chave pública correspondente (Res.-TSE nº 23.673, art. 15, caput).</li>
                   
                    <li>Último dia para o Tribunal Superior Eleitoral realizar audiência com as entidades interessadas em divulgar os resultados da eleição e apresentar a definição do modelo de distribuição e os padrões tecnológicos e de segurança exigidos para a divulgação dos resultados.</li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='9julho'>
               <li>
                  <div className={styles.dia}>9 de Julho - Terça-Feira </div>
                </li>
                <div>
                  <ol>
                    
                    <li>Data a partir da qual e até 30 de agosto de 2024, as juízas e os juízes deverão publicar edital contendo o nome das pessoas designadas como mesárias e mesários que atuarão nas seções instaladas em estabelecimentos penais e nas unidades de internação de adolescentes, no primeiro e no eventual segundo turnos de votação, contando-se da publicação do edital o prazo de 5 (cinco) dias para que os partidos políticos e federações reclamem das designações e para que as pessoas nomeadas, salvo se o impedimento for superveniente, apresentem recusa (Código Eleitoral, art. 120, § 4º; Lei nº 9.504/1997, art. 63, caput).</li>
                    
                    <li>Data a partir da qual e até 7 de agosto de 2024 as juízas e os juízes deverão publicar edital contendo o nome das pessoas designadas como mesárias e mesários e para prestar apoio logístico, incluídas as que atuarão nos testes de integridade das urnas eletrônicas, nas seções que não aquelas definidas no item 1 acima, no primeiro e no eventual segundo turnos de votação, contando-se da publicação do edital o prazo de 5 (cinco) dias para que os partidos políticos e federações reclamem das designações e para que as pessoas nomeadas, salvo se o impedimento for superveniente, apresentem recusa (Código Eleitoral, art. 120, § 4º; Lei nº 9.504/1997, art. 63, caput).</li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='12julho'>
                <li>
                  <div className={styles.dia}>12 de Julho - Sexta-Feira </div>
                </li>
                <div>
                  Início do prazo para cadastramento de agregação de seções eleitorais.
                </div>
              </section>
              
              <section className={styles.sec} id='16julho'>
                <li>
                  <div className={styles.dia}>16 de Julho - Terça-Feira </div>
                </li>
                <div>
                  Data a partir da qual e até 15 de agosto de 2024 e também nos 3 (três) dias que antecedem a eleição, o Tribunal Superior Eleitoral poderá divulgar comunicados, boletins e instruções ao eleitorado, em até 10 (dez) minutos diários requisitados às emissoras de rádio e de televisão, contínuos ou não, que poderão ser somados e usados em dias descontínuos, podendo ceder, a seu critério, parte desse tempo para utilização por tribunal regional eleitoral (Lei nº 9.504/1997, art. 93 e Res.-TSE nº 23.610, art. 115).
                </div>
              </section>
              
              <section className={styles.sec} id='19julho'>
                <li>
                  <div className={styles.dia}>19 de Julho - Sexta-Feira </div>
                </li>
                <div>
                  Data-limite para criação, no Cadastro Eleitoral, dos novos locais de votação onde funcionarão as seções eleitorais dos estabelecimentos penais e das unidades de internação de adolescentes, se ainda não existirem.
                </div>
              </section>
              
              <section className={styles.sec} id='20julho'>
                <li>
                  <div className={styles.dia}>20 de Julho - Sábado </div>
                </li>
                <div>
                  <ol>
                    
                    <li>Data a partir da qual e até 5 de agosto de 2024, os partidos políticos e as federações poderão realizar convenções para deliberar sobre coligações e escolher candidatas e candidatos aos cargos de prefeito, vice-prefeito e vereador (Lei nº 9.504/1997, art. 8º, caput e Res.-TSE nº 23.609, art. 6º).</li>
                    
                    <li>Data a partir da qual os partidos políticos e as federações deverão assegurar que, na data da convenção em cada Município:
                      <ul>
                        
                        <li>o partido político que deseje participar das eleições tenha órgão de direção constituído na circunscrição, devidamente anotado no tribunal regional eleitoral, de acordo com o respectivo estatuto partidário (Lei nº 9.504/1997, art. 4º; Res.-TSE nº 23.609/2019, art. 2º, I)</li>
                        
                        <li>a federação que deseje participar das eleições conte, em sua composição, com ao menos um partido político que tenha órgão de direção que atenda ao disposto no item a supra (Lei nº 9.504/1997, arts. 4º e 6º-A; e Res.- TSE nº 23.609/2019, art. 2º, II).</li>
                      </ul>
                    </li>
                    
                    <li>Data a partir da qual, observado o dia seguinte ao qual se realizou a convenção, os partidos políticos e as federações deverão transmitir pela internet a ata e a lista das pessoas presentes, digitadas no CANDex ou, na impossibilidade, entregá-las em mídia no cartório eleitoral, para publicação no sítio eletrônico da Justiça Eleitoral (Lei nº 9.504/1997, art. 8º, caput e Res.-TSE nº 23.609, art. 6º §§ 4º, I e 5º).</li>
                    
                    <li>Data a partir da qual a Justiça Eleitoral encaminhará à Secretaria da Receita Federal do Brasil os pedidos de inscrição no CNPJ das candidaturas, cujos registros tenham sido requeridos pelos partidos políticos, federações ou coligações, os quais deverão ser atendidos em até 3 (três) dias úteis (Lei nº 9.504/1997, art. 22-A, § 1º e Res.-TSE nº 23.609, art. 33, caput e I).</li>
                    
                    <li>Último dia para o Tribunal Superior Eleitoral publicar portaria com os limites de gastos de campanha estabelecidos em lei para cada cargo eletivo em disputa (Lei nº 9.504/1997, art. 18; e Res.-TSE nº 23.607/2019, art. 4º, § 2º).</li>
                    
                    <li>Data em que o Tribunal Superior Eleitoral divulgará, na internet, o quantitativo de eleitoras e eleitores por Município, para fins do cálculo do limite de gastos e do número de contratações diretas ou terceirizadas de pessoal para prestação de serviços referentes a atividades de militância e mobilização de rua nas campanhas eleitorais (Lei nº 9.504/1997, art. 100-A, Lei nº 13.488/2017, art. 6º e Res.-TSE nº 23.607, art. 41, § 4º).</li>
                    
                    <li>Data a partir da qual os partidos políticos, as candidatas e os candidatos deverão enviar à Justiça Eleitoral os dados sobre recursos financeiros recebidos para financiamento de sua campanha eleitoral, observado o prazo de 72 (setenta e duas) horas do recebimento desses recursos, para fins de divulgação na internet (Lei nº 9.504/1997, art. 28, § 4º, I; e Res.-TSE nº 23.607/2019, art. 47).</li>
                    
                    <li>Data a partir da qual, realizada a convenção para escolha de candidaturas, os partidos políticos, as candidatas e os candidatos poderão formalizar contratos que gerem despesas com a preparação da campanha e com a instalação física e virtual de comitês, desde que o desembolso financeiro ocorra após a obtenção do número de registro do CNPJ e a abertura de conta bancária específica (Res.-TSE nº 23.607/2019, art. 36, § 2º).</li>
                    
                    <li>Data a partir da qual é assegurado o exercício do direito de resposta à candidata, ao candidato, ao partido político, à federação ou à coligação atingida, ainda que de forma indireta, por conceito, imagem ou afirmação caluniosa, difamatória, injuriosa ou notoriamente inverídica, difundida por qualquer veículo de comunicação social, inclusive provedores de aplicativos de internet e redes sociais (Lei nº 9.504/1997, arts. 6º-A e 58, caput, Lei nº 9.096/1995, art. 11-A, caput e § 8º e Res.-TSE nº 23.608/2019, art. 31).</li>
                    
                    <li>Data-limite das novas totalizações de resultado da última eleição geral que serão consideradas no cálculo da representação de cada partido político na Câmara dos Deputados, para divisão do tempo destinado à propaganda eleitoral gratuita no rádio e na televisão (Lei nº 9.504/1997, art. 47, § 3º e Res.-TSE nº 23.610/2019, art. 55, § 1º).</li>
                    
                    <li> Data-limite das novas totalizações de resultado da última eleição geral que serão consideradas no cálculo da representação de cada partido político no Congresso Nacional, para fins da garantia prevista em lei para a participação em debates transmitidos por emissoras de rádio e de televisão (Lei nº 9.504/1997, art. 46, caput e Res.-TSE nº 23.610/2019, art. 44, § 6º).</li>
                    
                    <li>Data até a qual as emissoras de rádio e de televisão e demais veículos de comunicação, inclusive provedores de aplicações de internet, deverão, independente de intimação, apresentar ao órgão da Justiça Eleitoral definido pelo tribunal eleitoral, em meio físico ou eletrônico, a indicação da pessoa representante legal, dos endereços de correspondência e do correio eletrônico, e número de telefonia móvel que disponha de aplicativo de mensagens instantâneas pelos quais receberão ofícios, intimações ou citações, podendo indicar procuradora ou procurador com ou sem poderes para receber citação, hipótese em que farão juntar a respectiva procuração (Res.-TSE nº 23.608, art. 10 e Res.-TSE nº 23.610 /2019, art. 79).</li>
                    
                    <li>Data até a qual os provedores de aplicação da internet que pretendam prestar serviço de impulsionamento de propaganda eleitoral, inclusive sob a forma de priorização do resultado, deverão apresentar ao Tribunal Superior Eleitoral as informações que demonstrem o cumprimento das obrigações previstas no art. 27-A da Res.-TSE nº 23.610/2019(Res.-TSE nº 23.608, art. 10 e Res.-TSE nº 23.610, arts. 27-A e 29, §§ 3º e 9º)</li>
                    
                    <li>Data a partir da qual os nomes de todas as candidatas e candidatos registradas(os) deverão constar da lista apresentada às(aos) entrevistadas(os) durante a realização das pesquisas eleitorais (Res.-TSE nº 23.600/2019, art. 3º), observada a publicação dos editais de pedido de registro de candidaturas.</li>
                    
                    <li>Data a partir da qual os processos eleitorais, até 1° de novembro de 2024, terão prioridade para a participação do Ministério Público e dos juízos de todas as Justiças e instâncias, ressalvados as ações de habeas corpus e mandado de segurança (Lei nº 9.504/1997, art. 94, caput; e Res.-TSE nº 23.608/2019, art. 61).</li>
                    
                    <li>Data a partir da qual, até 1º de novembro de 2024, as polícias judiciárias, os órgãos das Receitas Federal, Estadual e Municipal, os tribunais e os órgãos de contas auxiliarão a Justiça Eleitoral na apuração dos delitos eleitorais, com prioridade sobre suas atribuições regulares (Lei nº 9.504/1997, art. 94, § 3º e Res.-TSE nº 23.608/2019, art. 61, § 3º).</li>
                    
                    <li>Data a partir da qual, desde a escolha em convenção até a diplomação das eleitas e dos eleitos, não podem atuar como juíza ou juiz eleitoral, juíza ou juiz membro ou auxiliar nos tribunais ou chefe de cartório, nos processos relativos às eleições municipais de 2024, a(o) cônjuge, a(o) companheira(o) e as(os) parentes consanguíneas(os) ou afim até o segundo grau de candidata ou de candidato a cargo eletivo registrada(o) na circunscrição (Código Eleitoral, arts. 14, § 3º e 33, § 1º; e Res.-TSE nº 23.608/2019, arts. 56 e 57).</li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='21julho'>
                <li>
                  <div className={styles.dia}>21 de Julho - Domingo </div>
                </li>
                <div>
                  Data a partir da qual será disponibilizada, na internet, consulta dos locais de votação com vagas para a transferência temporária de seção para militares, agentes de segurança pública, guardas municipais, juízas e juízes eleitorais, juízas e juízes auxiliares, servidoras e servidores da Justiça Eleitoral e promotoras e promotores eleitorais em serviço no dia das eleições.
                </div>
              </section>
              
              <section className={styles.sec} id='22julho'>
                <li>
                  <div className={styles.dia}>22 de Julho - Segunda-Feira </div>
                </li>
                <div>
                  <ol>
                    
                    <li>Data a partir da qual e até 22 de agosto de 2024, poderão habilitar-se, na Justiça Eleitoral, para votar em outra seção ou local, dentro do mesmo Município onde estão inscritas(os):
                      <ul>
                        
                        <li>presas e presos provisórias(os) e adolescentes em unidades de internação, mediante formulário próprio encaminhado pela administração dos estabelecimentos penais e das unidades de internação de adolescentes;</li>
                        
                        <li>militares, agentes de segurança pública e guardas municipais em serviço no dia da eleição, mediante listagem encaminhada pela chefia ou comando do órgão aos quais estiverem subordinadas;</li>
                        
                        <li>pessoas com deficiência ou com mobilidade reduzida;</li>
                        
                        <li>indígenas, quilombolas, integrantes de comunidades tradicionais e residentes de assentamentos rurais;</li>
                        
                        <li>juízas e juízes eleitorais, juízas e juízes auxiliares, servidoras e servidores da Justiça Eleitoral e promotoras e promotores eleitorais em serviço no dia das eleições, mediante listagem encaminhada pelo órgão ou unidade a que estiver vinculada(o) a eleitora ou o eleitor.</li>
                      </ul>
                    </li>
                    
                    <li>Data a partir da qual e até 30 de agosto de 2024, poderá habilitar-se na Justiça Eleitoral para votar, desde que no mesmo Município da sua inscrição eleitoral:
                      <ul>
                        
                        <li>a mesária ou o mesário, na seção em que atuará;</li>
                        
                        <li>a(o) convocada(o) para prestar apoio logístico, no local onde atuará;</li>
                        
                        <li>a(o) nomeada(o) para atuar nos testes de integridade das urnas eletrônicas, em local próximo ao evento;</li>
                        
                        <li>a(o) agente penitenciária(o), a(o) policial penal, a servidora ou o servidor de estabelecimentos penal ou de unidade de internação de adolescentes custodiadas(os), se estiver em serviço, na seção eleitoral do local, se for instalada.</li>
                      </ul>
                    </li>
                  </ol>
                </div>
              </section>
              
              <section className={styles.sec} id='26julho'>
                <li>
                  <div className={styles.dia}>26 de Julho - Sexta-Feira </div>
                </li>
                <div>
                  Último dia para a publicação do edital com os nomes das pessoas indicadas para compor as juntas eleitorais para o primeiro e eventual segundo turnos de votação, contando-se da data da publicação o prazo de 3 (três) dias para que partidos políticos e federações apresentem impugnação (Código Eleitoral, art. 36, § 2º).
                </div>
              </section>
              
              <section className={styles.sec} id='30julho'>
                <li>
                  <div className={styles.dia}>30 de Julho - Terça-Feira </div>
                </li>
                <div>
                  Data até a qual o Tribunal Superior Eleitoral promoverá, em até 5 (cinco) minutos diários, contínuos ou não, requisitados às emissoras de rádio e de televisão, propaganda institucional destinada a incentivar a participação feminina, das(os) jovens e da comunidade negra na política e a esclarecer cidadãs e cidadãos sobre as regras e o funcionamento do sistema eleitoral brasileiro (Lei nº 9.504/1997, art. 93-A; e Res.-TSE nº 23.610/2019, art. 116).
                </div>
              </section>
              
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Agosto</h1>
            <ul>
              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>5 de Junho - Terça-Feira</div>
                </li>
                <div>
                  Data-limite para o Tribunal Superior Eleitoral expedir as instruções relativas às eleições municipais de 2024 (Lei nº 9.504/1997, art. 105, caput e § 3º).
                </div>
              </section>
              

            <section className={styles.sec} id='5marco'>
              <li>
                <div className={styles.dia}>7 de Junho - Quinta-Feira</div>
              </li>
              <div>
                Data a partir da qual e até 5 de abril de 2024, considera-se justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
              </div>
            </section>
            </ul>
          </div>
          <div className={styles.mes}>
            <h1>Setembro</h1>
            <ul>
              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>5 de março - Terça-Feira</div>
                </li>
                <div>
                  Data-limite para o Tribunal Superior Eleitoral expedir as instruções relativas às eleições municipais de 2024 (Lei nº 9.504/1997, art. 105, caput e § 3º).
                </div>
              </section>
              

            <section className={styles.sec} id='5marco'>
              <li>
                <div className={styles.dia}>7 de março - Quinta-Feira</div>
              </li>
              <div>
                Data a partir da qual e até 5 de abril de 2024, considera-se justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
              </div>
            </section>
            
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Outubro</h1>
            <ul>
              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>5 de março - Terça-Feira</div>
                </li>
                <div>
                  Data-limite para o Tribunal Superior Eleitoral expedir as instruções relativas às eleições municipais de 2024 (Lei nº 9.504/1997, art. 105, caput e § 3º).
                </div>
              </section>
              

            <section className={styles.sec} id='5marco'>
              <li>
                <div className={styles.dia}>7 de março - Quinta-Feira</div>
              </li>
              <div>
                Data a partir da qual e até 5 de abril de 2024, considera-se justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
              </div>
            </section>
            
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Novembro</h1>
            <ul>
              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>5 de março - Terça-Feira</div>
                </li>
                <div>
                  Data-limite para o Tribunal Superior Eleitoral expedir as instruções relativas às eleições municipais de 2024 (Lei nº 9.504/1997, art. 105, caput e § 3º).
                </div>
              </section>
              

              <section className={styles.sec} id='5marco'>
                <li>
                  <div className={styles.dia}>7 de março - Quinta-Feira</div>
                </li>
                <div>
                  Data a partir da qual e até 5 de abril de 2024, considera-se justa causa para a desfiliação partidária de vereadoras e vereadores a mudança de partido para concorrer a cargo de prefeito ou de vereador (Lei nº 9.096/1995, art. 22-A, III).
                </div>
                
              </section>
            </ul>
            
          </div>
          <div className={styles.mes}>
            <h1>Dezembro</h1>
            <ul>
              <section className={styles.sec} id='5dezembro'>
                <li>
                  <div className={styles.dia}>5 de Dezembro - Quinta-Feira (60 dias após o 1° turno) </div>
                </li>
                <div>
                  Último dia para a eleitora ou o eleitor que deixou de votar no primeiro turno e que não justificou a falta no dia da eleição, apresentar, em qualquer cartório eleitoral, pelo aplicativo e-Título ou pelo serviço disponível no sítio eletrônico do TSE e dos TREs, justificativa fundamentada ao juízo eleitoral (Lei nº 6.091/1974, art. 16; Res.-TSE nº 23.659/2021, art. 126).
                </div>
              </section>
              <section className={styles.sec} id='11dezembro'>
                <li>
                  <div className={styles.dia}>11 de Dezembro - Quarta-Feira </div>
                </li>
                <div>
                  Último dia para o juízo eleitoral responsável pela recepção dos requerimentos de justificativa não registrados na urna no primeiro e no segundo turnos lançar as informações no Cadastro Eleitoral.                
                </div>
              </section>
              <section className={styles.sec} id='16dezembro'>
                <li>
                  <div className={styles.dia}>16 de Dezembro - Domingo</div>
                </li>
                <div>
                  Data até a qual, observada a antecedência de 3 (três) dias em relação à data da diplomação, deverão estar publicadas as decisões que julgarem as contas das candidatas e dos candidatos eleitas(os) (Lei nº 9.504/1997, art. 30, § 1º; e Res.-TSE nº 23.607/2019, art. 78).
                </div>
              </section>
              <section className={styles.sec} id='19dezembro'>
                <li>
                  <div className={styles.dia}>19 de Dezembro - Quinta-Feira</div>
                </li>
                <div>
                  <ol>
                    <li> Último dia para a diplomação das eleitas e dos eleitos.</li>
                    <li>Último dia para os cartórios eleitorais e secretarias dos tribunais eleitorais permanecerem abertos aos sábados, domingos e feriados (Lei Complementar nº 64/1990, art. 16).</li>
                    <li>Último dia de atuação das juízas e dos juízes auxiliares nos tribunais eleitorais (Lei nº 9.504/1997, art. 96, § 3º e Res.-TSE nº 23.608/2019, art. 2º, II).</li>
                    <li>Data a partir da qual os prazos processuais relativos aos processos das eleições de 2024 não mais serão mais contados, em cartório ou secretaria ou no PJe, de forma contínua (Lei Complementar nº 64/1990, art. 16; Res.-TSE nº 23.609/2019, art. 78; Res.-TSE nº 23.608/2019, art. 7º).</li>
                    <li>Último dia em que o mural eletrônico, mensagens instantâneas e mensagens eletrônicas serão utilizados para as comunicações da Justiça Eleitoral nos processos de registro de candidatura, nas representações, nas reclamações, nos pedidos de direito de resposta e nas prestações de contas, observadas as regras específicas das respectivas resoluções (Res.-TSE nº 23.607/2019, art. 98, caput; Res.-TSE nº 23.608/2019, caput, art. 12 e Res.-TSE nº 23.609/2019, art. 38, caput).</li>
                    <li>Último dia em que, nas representações, nas reclamações, nos pedidos de direito de resposta e nas prestações de contas, o Ministério Público será intimado das decisões e dos despachos por meio eletrônico (Res.-TSE nº 23.607/2019, art. 99 e Res.-TSE nº 23.608/2019, art. 12, §§ 7º e 8º).</li>
                    <li>Último dia em que o Ministério Público e as partes serão intimados dos acórdãos, em sessão de julgamento, quando nela forem publicados. (Res.- TSE nº 23.607/2019, art. 99; Res.-TSE nº 23.608/2019, art. 12, §§ 7º e 8º; e Res.- TSE nº 23.609/2019, art. 38, §§ 7º e 8º).</li>
                    <li>Último dia em que, nos procedimentos de registro de candidatura, propaganda eleitoral, direito de resposta e prestação de contas, a publicação dos atos judiciais será realizada em mural eletrônico, disponível no sítio eletrônico do respectivo tribunal, com o registro do horário da publicação, e os acórdãos serão publicados em sessão de julgamento (Res.-TSE nº 23.607/2019, art. 99; Res.- TSE nº 23.608/2019, art. 12, caput e § 9ºRes.-TSE nº 23.609/2019, art. 38, caput e § 9º).</li>
                  </ol>
                </div>
              </section>
              <section className={styles.sec} id='31dezembro'>
                <li>
                  <div className={styles.dia}>31 de Dezembro - Terça-Feira</div>
                </li>
                <div>
                  <ol>
                    <li>Data-limite para os bancos encerrarem as contas bancárias das candidatas e dos candidatos destinadas à movimentação de recursos do Fundo Partidário e de doações para campanha, transferindo a totalidade do saldo existente para a conta bancária do órgão de direção da circunscrição, na forma prevista no art. 51 da Res-TSE nº 23.607/2019, informando o fato à Justiça Eleitoral (Res.-TSE nº 23.607/2019, art. 12, III).</li>
                    <li>Data-limite para os bancos encerrarem as contas bancárias das candidatas, dos candidatos e dos partidos políticos destinadas à movimentação de recursos do Fundo Especial de Financiamento de Campanha (FEFC) transferindo, de forma unificada, a totalidade do saldo existente para o Tesouro Nacional, na forma prevista no art. 52 Resolução-TSE nº 23.607/2019, informando o fato à Justiça Eleitoral (Res.-TSE nº 23.607/2019, art. 12, IV).</li>
                    <li>Data em que todas as inscrições das candidatas e dos candidatos na Receita Federal serão, de ofício, canceladas (Instrução Normativa Conjunta-RFB/TSE nº 2001/2020, art. 7º, I).</li>
                  </ol>
                </div>
              </section>


          
            </ul>
            
          </div>
        </div>
      </main>
    </>
  )
}